#!/usr/bin/env bash

set -e

host="$1"
if [[ -f flake.nix ]]; then
  repo="$(pwd)"
else
  repo="github:ReStranger/nixos-config"
fi
ref="$repo#$host"

rm -f /etc/nix/nix.conf
nix build \
    -o /etc/nix/nix.conf \
    --extra-experimental-features 'nix-command flakes' \
    "${repo}#nixosConfigurations.${host}.config.environment.etc.\"nix/nix.conf\".source"
systemctl restart nix-daemon.service

if [[ "${INSTALL:-1}" != "0" ]]; then
  nixos-install --flake "$ref"
fi

unmnt="umount -R /mnt"
if [[ "${UMOUNT:-1}" != "0" ]]; then
  echo unmount: "$unmnt"
  eval "$unmnt"
fi
