{
  imports =
    [
      ./adb.nix
      ./boot.nix
      ./fstab.nix
      ./greetd-tui.nix
      ./hyprland.nix
      ./locale.nix
      ./networking.nix
      ./nix.nix
      ./pipewire.nix
      ./polkit.nix
      ./services.nix
      ./timezone.nix
      ./tty.nix
      ./users.nix
      ./zapret.nix
      ./zram.nix
    ];
}
